var name ="";
var email ="";
var username ="";
var password ="";
var repassword =  "";
var type ="";
var rand = "";
var loginusername = "";
var loginpwdtoggler = "";
var activeuser = "";

module.exports.name;
module.exports.email;
module.exports.username;
module.exports.password;
module.exports.repassword;
module.exports.type;
module.exports.rand;
module.exports.loginusername;
module.exports.loginpwdtoggler;
module.exports.activeuser;